GET http://localhost:80/
###

GET http://localhost:80/list
###

POST http://localhost:80/add

{
    "key": "herdllo",
    "value": "another sample value"
}
### 

POST http://localhost:80/add

{
    "key": "d",
    "value": "some other value"
}
### 

POST  http://localhost:80/data/hello

{
    "key": "hello",
    "value": "some other value"
}
### 
GET  http://localhost:80/data
### 
PUT  http://localhost:80/data/d

{
    "key": "d",
    "value": "some fjeisjf"
}
### 
DELETE  http://localhost:80/data/herdllo
### 